export CUDA_VISIBLE_DEVICES=1,2,3,4
set -euo pipefail

###################################
# User Configuration Section
###################################
RUN_PYTHON_PATH="/data/wyf/conda_envs/diffusion_planner/bin/python" # python path (e.g., "/home/xxx/anaconda3/envs/diffusion_planner/bin/python")
USE_SUDO="false" # set to true only when root privileges are really required
TRAIN_EXTRA_ARGS="--batch_size 512 --num_workers 2" # lower per-GPU memory usage; tune if still OOM

# Set training data path
TRAIN_SET_PATH="/data/wyf/lgq/nuplan/dataset/nuplan-v1.1/splits/train_processed" # output path from data_process.sh
TRAIN_SET_LIST_PATH="/data/wyf/lgq/nuplan/dataset/nuplan-v1.1/splits/train_processed/train_list.json" # list generated by data_process.py
###################################

if [[ ! -x "$RUN_PYTHON_PATH" ]]; then
	echo "[ERROR] Python not executable: $RUN_PYTHON_PATH"
	exit 1
fi

if [[ ! -d "$TRAIN_SET_PATH" ]]; then
	echo "[ERROR] Train set dir not found: $TRAIN_SET_PATH"
	exit 1
fi

if [[ ! -f "$TRAIN_SET_LIST_PATH" ]]; then
	echo "[ERROR] Train set list not found: $TRAIN_SET_LIST_PATH"
	echo "Run preprocessing first: bash data_process.sh"
	exit 1
fi

NPZ_COUNT=$(find "$TRAIN_SET_PATH" -maxdepth 1 -name '*.npz' | wc -l)
if [[ "$NPZ_COUNT" -eq 0 ]]; then
	echo "[ERROR] No npz files found in: $TRAIN_SET_PATH"
	exit 1
fi

NPROC_PER_NODE=$(echo "$CUDA_VISIBLE_DEVICES" | awk -F',' '{print NF}')
if [[ "$NPROC_PER_NODE" -le 0 ]]; then
	echo "[ERROR] Invalid CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
	exit 1
fi

echo "Using TRAIN_SET_PATH=$TRAIN_SET_PATH"
echo "Using TRAIN_SET_LIST_PATH=$TRAIN_SET_LIST_PATH"
echo "Detected NPROC_PER_NODE=$NPROC_PER_NODE"

LAUNCH_CMD=("$RUN_PYTHON_PATH" -m torch.distributed.run --nnodes 1 --nproc-per-node "$NPROC_PER_NODE" --standalone train_predictor.py \
	--train_set "$TRAIN_SET_PATH" \
	--train_set_list "$TRAIN_SET_LIST_PATH")

if [[ -n "$TRAIN_EXTRA_ARGS" ]]; then
	# shellcheck disable=SC2206
	EXTRA_ARR=($TRAIN_EXTRA_ARGS)
	LAUNCH_CMD+=("${EXTRA_ARR[@]}")
fi

if [[ "$USE_SUDO" == "true" ]]; then
	sudo -E "${LAUNCH_CMD[@]}"
else
	"${LAUNCH_CMD[@]}"
fi

